
#include <plib.h>

void initADC() {
    CloseADC10();
    SetChanADC10(ADC_CH0_NEG_SAMPLEA_NVREF);
    OpenADC10(    ADC_FORMAT_INTG16 | ADC_CLK_AUTO | ADC_AUTO_SAMPLING_ON ,
            ADC_VREF_AVDD_AVSS | ADC_OFFSET_CAL_DISABLE | ADC_SCAN_ON | ADC_SAMPLES_PER_INT_2 | ADC_ALT_BUF_OFF | ADC_ALT_INPUT_OFF,
            ADC_CONV_CLK_PB | ADC_SAMPLE_TIME_15 | ADC_CONV_CLK_Tcy,
            ENABLE_AN11_ANA | ENABLE_AN9_ANA, 
            //SKIP_SCAN_ALL
            SKIP_SCAN_AN0 |SKIP_SCAN_AN1 |SKIP_SCAN_AN2 |SKIP_SCAN_AN3 |SKIP_SCAN_AN4 |SKIP_SCAN_AN5 |SKIP_SCAN_AN6 |SKIP_SCAN_AN7 |SKIP_SCAN_AN8 |
            SKIP_SCAN_AN10 |SKIP_SCAN_AN12 |SKIP_SCAN_AN13 |SKIP_SCAN_AN14 |SKIP_SCAN_AN15
            );
    
    EnableADC10(); // The claw tends towards Entropy


}
